# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhello.proto\x12\tgrpc_demo\"\x13\n\x03req\x12\x0c\n\x04user\x18\x01 \x01(\t\"\x13\n\x04resp\x12\x0b\n\x03msg\x18\x01 \x01(\t2=\n\x0cHelloService\x12-\n\x08SayHello\x12\x0e.grpc_demo.req\x1a\x0f.grpc_demo.resp\"\x00\x42\x0cZ\ngrpc_demo/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\ngrpc_demo/'
  _globals['_REQ']._serialized_start=26
  _globals['_REQ']._serialized_end=45
  _globals['_RESP']._serialized_start=47
  _globals['_RESP']._serialized_end=66
  _globals['_HELLOSERVICE']._serialized_start=68
  _globals['_HELLOSERVICE']._serialized_end=129
# @@protoc_insertion_point(module_scope)
